realisations:
  - repo:
      git:
        branch: main
  - repo:
      git:
        branch: 123-benchcab-demo
    meorg_output_name: true

fluxsite:
  experiment: five-site-test

modules: [
  intel-compiler/2021.10.0,
  netcdf/4.7.4,
  openmpi/4.1.0
]
