## science configs
#

sci0: {
    cable_user: {
        GS_SWITCH: "medlyn",
        FWSOIL_SWITCH: "Haverd2013"
    }
}

sci1: {
    cable_user: {
        GS_SWITCH: "leuning",
        FWSOIL_SWITCH: "Haverd2013"
    }
}

sci2: {
    cable_user: {
        GS_SWITCH: "medlyn",
        FWSOIL_SWITCH: "standard"
    }
}
sci3: {
    cable_user: {
        GS_SWITCH: "leuning",
        FWSOIL_SWITCH: "standard"
    }
}

